// Alert
export const ALERT_SUCCESS = "ALERT_SUCCESS";
export const ALERT_ERROR = "ALERT_ERROR";

// User Authentication
export const LOADING_USER_LOGIN = "LOADING_USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

// Services
export const ADDING_SERVICE_START = "ADDING_SERVICE_START";
export const ADD_SERVICE_SUCCESS = "ADD_SERVICE_SUCCESS";
export const ADD_SERVICE_FAIL = "ADD_SERVICE_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";